/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dirprintergui;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author tpaulson
 */
public class dirPrtGUI extends javax.swing.JFrame
{
    int countDir = 0; 
    int countFile = 0;

    /**
     * Creates new form dirPrtGUI
     */
    public dirPrtGUI()
    {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        pathTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        exitBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        printContentsBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDisplayArea = new javax.swing.JTextArea();
        itemsCountLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Copy and paste the file path you would like to start at into the text field below.");

        pathTF.setToolTipText("ENTER THE FILE PATH HERE");

        jLabel2.setText("File Path: ");

        exitBTN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitBTNActionPerformed(evt);
            }
        });

        resetBTN.setText("RESET");
        resetBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetBTNActionPerformed(evt);
            }
        });

        printContentsBTN.setText("PRINT CONTENTS");
        printContentsBTN.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printContentsBTNActionPerformed(evt);
            }
        });

        textDisplayArea.setColumns(20);
        textDisplayArea.setRows(5);
        jScrollPane1.setViewportView(textDisplayArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathTF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(itemsCountLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBTN)
                        .addGap(18, 18, 18)
                        .addComponent(exitBTN))
                    .addComponent(jLabel1)
                    .addComponent(printContentsBTN))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printContentsBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBTN)
                    .addComponent(itemsCountLBL)
                    .addComponent(resetBTN))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void printContentsBTNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printContentsBTNActionPerformed
        {//GEN-HEADEREND:event_printContentsBTNActionPerformed
            // try{
            String input = pathTF.getText();

            File currentDir = new File(input); // current directory
            textDisplayArea.append("Starting file path entered:  " + input + "\n\n");

            displayDirectoryContents(currentDir);
               //}catch (NullPointerException e){
            //textDisplayArea.append("****Please enter a valid path****\n\n CLICK THE RESET BUTTON");
            //}
            textDisplayArea.append("\nTotal Directories:  "+Integer.toString(countDir) + "\nTotal Files:  " + Integer.toString(countFile));
            
        }//GEN-LAST:event_printContentsBTNActionPerformed

        private void resetBTNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetBTNActionPerformed
        {//GEN-HEADEREND:event_resetBTNActionPerformed
            textDisplayArea.setText(null);
            pathTF.setText(null);

        }//GEN-LAST:event_resetBTNActionPerformed

        private void exitBTNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitBTNActionPerformed
        {//GEN-HEADEREND:event_exitBTNActionPerformed
            System.exit(0);
        }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(dirPrtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(dirPrtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(dirPrtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(dirPrtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new dirPrtGUI().setVisible(true);

            }//end run

        });
    }//end main()
    
   
    

    public void displayDirectoryContents(File dir)
    {
        try
        {         
            File[] files = dir.listFiles();
            for (File file : files)
            {
                if (file.isDirectory())
                {
                    countDir();
                    textDisplayArea.append("\nDIRECTORY:" + file.getCanonicalPath() + "\n");
                    displayDirectoryContents(file);
                } else
                {
                    countFile();
                    textDisplayArea.append("     File:  " + file.getName() + "\n");
                }
                
            }//end for
            
        } catch (IOException e)
        {
            e.printStackTrace();
        }
    
    }//end method isplayDirectoryContents
    
     public int countDir(){
        countDir ++;
        return countDir;   
    }
    
    public int countFile(){
        countFile ++;
        return countFile;   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel itemsCountLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pathTF;
    private javax.swing.JButton printContentsBTN;
    private javax.swing.JButton resetBTN;
    private javax.swing.JTextArea textDisplayArea;
    // End of variables declaration//GEN-END:variables
}//end class

